title: Trang blog của Trai IT
author: Trai IT
email: traiit.blogger@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Xin chào các bạn đến với trang blog của Trai IT.
  Sao mình lại đặt là "Trai IT"? Đơn giản là mình đang là một chàng sinh viên IT. Mà "Trai IT" like "traɪ it" like "try it".
  Đúng vậy phải "try"! Mình sẽ chia sẻ về đời sống và công nghệ theo cách nhìn và tiếp cận của mình, rất cảm ơn các bạn
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Trai IT
  tagline: Programmer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    twitter: traiit
    github:  traiit
    linkedIn: in/traiit
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
